### ISSUE TITLE
Dkron instance goes down with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rishavanand** [distribworks/dkron#1022]
**Describe the bug**
Dkron goes down randomly with invalid memory address or nil pointer dereference error.

**To Reproduce**
I'm not sure how to reproduce it. It happens randomly. 

**Expected behavior**
Dkron should not go down. 

** Specifications:**
 - OS: Ubuntu
 - Version 20.04

**Additional context**
Logs:

```
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="received response code does not match the expected code" job=req_id_259600543a9b4c4f58839de3576candidate_action_pedning node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_32202_smart_match node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_265610f02946d64ba9e3e5d4d01offer node=904cddf34484
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="Post \"None/api/jobreq/cronjob/smart_match_notifications/\": unsupported protocol scheme \"\"" job=req_id_28402_smart_match node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_14960fae87d6b32340d30ef6181offer node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_46041c7524113f4e1ae6b0d75cp_has_shortlisted node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_45602f43414113f4e1aee1ca1fcp_has_shortlisted node=904cddf34484
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="Post \"https://xxxxxxxxxxxxx.com/api/jobreq/cronjob/shortlist_notifications/\": dial tcp: lookup xxxxxxxxxxxxx.com on 172.31.0.2:53: no such host" job=req_id_45602f43414113f4e1aee1ca1fcp_has_shortlisted node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_15260fbfc356b32340d30f85b13offer node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="received response code does not match the expected code" job=id_454545t5f9b140c6f8321c3e32c8647candidate_action_pedning node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_202_smart_match node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=id_707070test02_smart_match node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_46560179a7c267e4f1b3c40a1f1cp_has_shortlisted node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_2776018ef09267e4f1b3c504af9candidate_action_pedning node=904cddf34484
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_53601e8cfb4113f4e1ae80b6fccp_has_shortlisted node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_261610f02856d64ba9e3e5d4ba4offer node=904cddf34484
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_50702_smart_match node=904cddf34484
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_5606057146c267e4f1b3cff73f7offer node="172.17.0.2:6868"
time="2021-09-21T17:27:24Z" level=info msg="grpc_agent: Starting job" job=req_id_4602_smart_match node=904cddf34484
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="Post \"None/api/jobreq/cronjob/smart_match_notifications/\": unsupported protocol scheme \"\"" job=req_id_4602_smart_match node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=error msg="grpc_agent: command error output" error="received response code does not match the expected code" job=req_id_265610f02946d64ba9e3e5d4d01offer node=904cddf34484 plugin="&{0xc000281500 0xc0007bb2c0}"
time="2021-09-21T17:27:24Z" level=info msg="agent: Calling AgentRun" job_name=req_id_592605daddb267e4f1b3c456490offer node="172.17.0.2:6868"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x97caaa]

goroutine 365545 [running]:
google.golang.org/grpc.(*Server).Stop(0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1626 +0x4a
github.com/distribworks/dkron/v3/plugin.(*ExecutorClient).Execute(0xc00000d140, 0xc05632c550, 0x32dd020, 0xc055bff4b8, 0xc055a7f4d0, 0x1, 0x203015)
	/home/runner/work/dkron/dkron/plugin/executor.go:65 +0x198
github.com/distribworks/dkron/v3/dkron.(*AgentServer).AgentRun(0xc00007f400, 0xc056302dc0, 0x332d458, 0xc056310a50, 0x0, 0x0)
	/home/runner/work/dkron/dkron/dkron/grpc_agent.go:87 +0x710
github.com/distribworks/dkron/v3/plugin/types._Agent_AgentRun_Handler(0x2137000, 0xc00007f400, 0x3328860, 0xc05584e240, 0x42d76e8, 0xc05632aa20)
	/home/runner/work/dkron/dkron/plugin/types/dkron_grpc.pb.go:540 +0x113
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000ae0700, 0x33337d8, 0xc056346180, 0xc05632aa20, 0xc000e98bd0, 0x426c340, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1464 +0xcd8
google.golang.org/grpc.(*Server).handleStream(0xc000ae0700, 0x33337d8, 0xc056346180, 0xc05632aa20, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1544 +0xca5
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc055dceee0, 0xc000ae0700, 0x33337d8, 0xc056346180, 0xc05632aa20)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
time="2021-09-21T17:27:24Z" level=info msg="No valid config found: Applying default values." error="Config File \"dkron\" Not Found in \"[/etc/dkron /root/.dkron /opt/local/dkron/config]\""
time="2021-09-21T17:27:25Z" level=info msg="agent: Dkron agent starting" node=904cddf34484
time="2021-09-21T17:27:25Z" level=info msg="agent: joining: [] replay: true" node=904cddf34484
time="2021-09-21T17:27:25Z" level=info msg="api: Running HTTP server" address=":8080" node=904cddf34484


2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)



2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)



2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)



2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)



2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)



2021/09/21 17:27:25 [Recovery] 2021/09/21 - 17:27:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:212 (0x434cba)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/signal_unix.go:734 (0x44dad2)
/home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d83a8b)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1daf9a2)
/home/runner/work/dkron/dkron/dkron/api.go:128 (0x1daf985)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d825ae)
/home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82594)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc43e39)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc43e20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc42f13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc42ed2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39649)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc3962f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc3911b)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x7233a2)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x71e7cc)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46da20)

time="2021-09-21T17:28:04Z" level=info msg="agent: registering usage stats for cluster ID 'H/vWkHciuGdiSOi2GA5hmiyxsIq8DN1OWu9cEiAJC68='" node=904cddf34484
time="2021-09-21T17:28:04Z" level=info msg="dkron: monitoring leadership" node=904cddf34484
time="2021-09-21T17:28:04Z" level=info msg="agent: Listen for events" node=904cddf34484
time="2021-09-21T17:28:04Z" level=info msg="agent: Received event" event=member-join node=904cddf34484
time="2021-09-21T17:28:04Z" level=info msg="adding server" node=904cddf34484 server=904cddf34484
time="2021-09-21T17:28:05Z" level=info msg="agent: Received event" event=member-update node=904cddf34484
time="2021-09-21T17:28:06Z" level=info msg="dkron: cluster leadership acquired" node=904cddf34484
time="2021-09-21T17:28:06Z" level=info msg="dkron: monitoring leadership" node=904cddf34484
time="2021-09-21T17:28:24Z" level=info msg="agent: Starting scheduler" node=904cddf34484
```

**Comment by yvanoers** [comment]
Please update to 3.1.10.
v.3.1.8 was the last release that did not have this issue addressed.

I'll close the issue now, but please reopen if this remains an issue for you with the latest release.
