### ISSUE TITLE
panic: neither raftInmem or raftStore is initialized

### ISSUE THREAD

**Issue by tolgaulas** [distribworks/dkron#1110]
When an agent (config.server=false) is trying to connect to a server (config.server=true), the below error interrupts the process, documentation has no mention on this detail:
```
msg="agent: Joining cluster..." cluster=LAN node=agent
msg="agent: Join LAN completed. Synced with 1 initial agents" node=agent
msg="agent: Listen for events" node=agent
msg="agent: Received event" event=member-update node=agent
msg="agent: Received event" event=member-join node=agent
msg="adding server" node=kannemulator server=server
panic: neither raftInmem or raftStore is initialized
goroutine 188 [running]:
github.com/distribworks/dkron/v3/dkron.(*Agent).maybeBootstrap(0xc000d18c60)
         /home/runner/work/dkron/dkron/dkron/serf.go:68 +0x1095
github.com/distribworks/dkron/v3/dkron.(*Agent).nodeJoin(0xc000d18c60, 0x0, 0xc000fd0280, 0x1, 0x1)
         /home/runner/work/dkron/dkron/dkron/serf.go:51 +0x456
github.com/distribworks/dkron/v3/dkron.(*Agent).eventLoop(0xc000d18c60)
        /home/runner/work/dkron/dkron/dkron/agent.go:684 +0xa0d
created by github.com/distribworks/dkron/v3/dkron.(*Agent).Start
         /home/runner/work/dkron/dkron/dkron/agent.go:219 +0x630
dkron.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Failed with result 'exit-code'.
```

however, when agent is put in server mode (config.server=true) the connection is established however the server is not displayed as leader (and even after removing the server=true from config of agent, the connection is established but still no leader):

config of server:
```
server:true
bootstrap-expect: 1
bind-addr: "publicip_of_server:8946"
```
config of agent:
```
bind-addr: "publicip_of_agent:8946"
retry-join:
   - publicip_of_server
```

** Specifications:**
 - OS: debian 10 buster on both end..
 - dkron v3.1.11

**Comment by vcastellm** [comment]
What version?

**Comment by tolgaulas** [comment]
> What version?
v.3.1.11

**Comment by tolgaulas** [comment]
latest, just installed on the ticket date.
Tolga Ulas
+90 533 7464908, skypeid:tolgaulas

**Comment by yxxhero** [comment]
I meet this issue.

**Comment by yxxhero** [comment]
version: 3.2.1

**Comment by vcastellm** [comment]
Unable to reproduce

**Comment by durch** [comment]
If anyone stumbles upon this, try removing the `bootstrap_expect` line from your config.
