### ISSUE TITLE
Context Deadline Exceeded error

### ISSUE THREAD

**Issue by brynette-stewart** [distribworks/dkron#574]
## Expected Behavior
Can successfully post and run a job.

## Actual Behavior
Job attempts to run and fails with a "context deadline exceeded"

## Steps to Reproduce the Problem
This only happens in a k8 stateful set.
```
agent
  --server
  --backend=dynamodb
  --backend-machine=dynamodb.us-east-1.amazonaws.com
  --join=dkron-jobs-service.default.svc.cluster.local:8946
  --log-level=debug
  --http-addr=8089
```

Job
```
{"name":"here_goes_nothing","schedule":"@every 5s","shell":true,"command":"echo test","tags":{"role":"digital-trust:1"},"retries":2,"disable":false,"concurrency":"forbid"}
```

## Specifications

  - Version: v1.2.2
  - Platform: Linux
  - Backend store: DynamoDB

**Comment by victorcoder** [comment]
Hi @brynette-stewart, could you post here the relevant output log? Thanks

**Comment by AyrtonSparling** [comment]
```
$ sudo docker logs -f dkron
time="2019-07-24T03:30:38Z" level=info msg="No valid config found: Applying default values." error="Config File \"dkron\" Not Found in \"[/etc/dkron /root/.dkron /opt/local/dkron/config]\""
time="2019-07-24T03:30:38Z" level=info msg="agent: Dkron agent starting" node=bf24de47716e
time="2019-07-24T03:30:38Z" level=info msg="agent: joining: [] replay: false" node=bf24de47716e
badger 2019/07/24 03:30:38 INFO: All 0 tables opened in 0s
time="2019-07-24T03:30:38Z" level=info msg="api: Running HTTP server" address=":8080" node=bf24de47716e
time="2019-07-24T03:30:38Z" level=info msg="dkron: monitoring leadership" node=bf24de47716e
time="2019-07-24T03:30:38Z" level=info msg="agent: Listen for events" node=bf24de47716e
time="2019-07-24T03:30:39Z" level=info msg="agent: Received event" event=member-update node=bf24de47716e
time="2019-07-24T03:31:39Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=bf24de47716e server_addr=
```

While trying to run
```
curl localhost:8080/v1/jobs -XPOST -d '{
  "name": "job1",
  "schedule": "@every 10s",
  "timezone": "Europe/Berlin",
  "owner": "Platform Team",
  "owner_email": "platform@example.com",
  "disabled": false,
  "tags": {
    "dkron_server": "true:1"
  },
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "date"
  }
}'
```

**Comment by AyrtonSparling** [comment]
Got it working with `--bootstrap-expect=1`. Thanks.

**Comment by randallsquared** [comment]
@AyrtonSparling I believe there are two separate situations for this problem: 

1. immediately after startup or config reload, and 
2. when a job tries to run

**Comment by brynette-stewart** [comment]
@victorcoder Sorry for the delay. Here are the logs.
```
time="2019-07-25T15:43:45Z" level=debug msg="scheduler: Adding job to cron" job=here_goes_nothing7 node=dkron-jobs-0
time="2019-07-25T15:43:48Z" level=debug msg="agent: Done receiving acks and responses" node=dkron-jobs-0 query="scheduler:restart"
time="2019-07-25T15:44:00Z" level=debug msg="scheduler: Run job" job=here_goes_nothing7 node=dkron-jobs-0 schedule="@every 15s"
time="2019-07-25T15:44:00Z" level=debug msg="store: Retrieved job from datastore" job=here_goes_nothing7 node=dkron-jobs-0
time="2019-07-25T15:44:00Z" level=debug msg="agent: Filtered nodes to run: []" node=dkron-jobs-0
time="2019-07-25T15:44:00Z" level=debug msg="agent: Filtered tags to run: map[]" node=dkron-jobs-0
time="2019-07-25T15:44:00Z" level=info msg="agent: Sending query" job_name=here_goes_nothing7 node=dkron-jobs-0 query="run:job"
time="2019-07-25T15:44:00Z" level=debug msg="agent: Sending query" job_name=here_goes_nothing7 json="{\"execution\":{\"job_name\":\"here_goes_nothing7\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1564069440046999876,\"attempt\":1},\"rpc_addr\":\"172.30.79.9:6868\"}" node=dkron-jobs-0 query="run:job"
time="2019-07-25T15:44:00Z" level=info msg="agent: Received event" event="query: run:job" node=dkron-jobs-0
time="2019-07-25T15:44:00Z" level=debug msg="agent: Running job" at=2 node=dkron-jobs-0 payload="{\"execution\":{\"job_name\":\"here_goes_nothing7\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1564069440046999876,\"attempt\":1},\"rpc_addr\":\"172.30.79.9:6868\"}" query="run:job"
time="2019-07-25T15:44:00Z" level=info msg="agent: Starting job" job=here_goes_nothing7 node=dkron-jobs-0
time="2019-07-25T15:44:00Z" level=info msg="2019/07/25 15:44:00 [DEBUG] serf: messageQueryResponseType: dkron-jobs-0"
time="2019-07-25T15:44:00Z" level=debug msg="agent: Received ack" from=dkron-jobs-0 node=dkron-jobs-0 query="run:job"
time="2019-07-25T15:44:03Z" level=debug msg="agent: Done receiving acks and responses" node=dkron-jobs-0 query="run:job"
time="2019-07-25T15:44:05Z" level=error msg="grpc: error dialing." err="context deadline exceeded" node=dkron-jobs-0 server_addr="172.30.79.9:6868"
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x83cc62]

goroutine 169 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.18.0/clientconn.go:853 +0x42
panic(0x11529c0, 0x2012dc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
google.golang.org/grpc.(*ClientConn).Invoke(0x0, 0x16147a0, 0xc00003c058, 0x12f0cbf, 0x13, 0x1229820, 0xc00060fcb0, 0x12afa40, 0xc00015c3c0, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.18.0/call.go:32 +0x38
github.com/victorcoder/dkron/proto.(*dkronClient).GetJob(0xc00000ea80, 0x16147a0, 0xc00003c058, 0xc00060fcb0, 0x0, 0x0, 0x0, 0x202cc60, 0xc000595680, 0x3)
	/dkron/proto/dkron.pb.go:400 +0xd2
github.com/victorcoder/dkron/dkron.(*GRPCClient).CallGetJob(0xc00048fdc0, 0xc00076cc50, 0x10, 0xc000742de0, 0x12, 0x0, 0x0, 0x0)
	/dkron/dkron/grpc.go:272 +0x22c
github.com/victorcoder/dkron/dkron.(*Agent).eventLoop(0xc0000ec280)
	/dkron/dkron/agent.go:472 +0x14e8
created by github.com/victorcoder/dkron/dkron.(*Agent).Start
	/dkron/dkron/agent.go:103 +0x3b9
```
And we are using version 1.2.2 so it doesnt seem like the `--bootstrap-expect` flag is relevant for this use case.

**Comment by mandeepbal** [comment]
When I tried running the command you posted @AyrtonSparling , I had a similar failure. 

### command
```
curl -X POST http://172.30.103.10:8089/v1/jobs -XPOST -d '{
>     "name": "job1",
>     "schedule": "@every 10s",
>     "timezone": "Europe/Berlin",
>     "owner": "Platform Team",
>     "owner_email": "platform@example.com",
>     "disabled": false,
>     "tags": {
>       "dkron_server": "true:1"
>     },
>     "concurrency": "allow",
>     "executor": "shell",
>     "executor_config": {
>       "command": "date"
>     }
>   }'
{"name":"job1","timezone":"Europe/Berlin","schedule":"@every 10s","owner":"Platform Team","owner_email":"platform@example.com","success_count":0,"error_count":0,"last_success":"0001-01-01T00:00:00Z","last_error":"0001-01-01T00:00:00Z","disabled":false,"tags":{"dkron_server":"true:1"},"retries":0,"dependent_jobs":null,"parent_job":"","processors":null,"concurrency":"allow","executor":"shell","executor_config":{"command":"date"},"status":"","next":"0001-01-01T00:00:00Z"}
```

### container logs
```time="2019-07-30T18:57:18Z" level=debug msg="store: Setting job" job=job1 json="{\"name\":\"job1\",\"timezone\":\"Europe/Berlin\",\"schedule\":\"@every 10s\",\"owner\":\"Platform Team\",\"owner_email\":\"platform@example.com\",\"success_count\":0,\"error_count\":0,\"last_success\":\"0001-01-01T00:00:00Z\",\"last_error\":\"0001-01-01T00:00:00Z\",\"disabled\":false,\"tags\":{\"dkron_server\":\"true:1\"},\"retries\":0,\"dependent_jobs\":null,\"parent_job\":\"\",\"processors\":null,\"concurrency\":\"allow\",\"executor\":\"shell\",\"executor_config\":{\"command\":\"date\"},\"status\":\"\",\"next\":\"0001-01-01T00:00:00Z\"}" node=dkron-jobs-0
time="2019-07-30T18:57:18Z" level=info msg="[GIN] 2019/07/30 - 18:57:18 | 201 |   45.299847ms |     172.30.87.0 | POST     /v1/jobs" node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=debug msg="store: Retrieved leader from datastore" node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=info msg="agent: Received event" event="query: scheduler:restart" node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=info msg="agent: Restarting scheduler" node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=info msg="2019/07/30 18:57:21 [DEBUG] serf: messageQueryResponseType: dkron-jobs-0"
time="2019-07-30T18:57:21Z" level=debug msg="agent: Received ack" from=dkron-jobs-0 node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=debug msg="scheduler: Stopping scheduler" node=dkron-jobs-0
time="2019-07-30T18:57:21Z" level=debug msg="scheduler: Adding job to cron" job=job1 node=dkron-jobs-0
time="2019-07-30T18:57:24Z" level=debug msg="agent: Done receiving acks and responses" node=dkron-jobs-0 query="scheduler:restart"
time="2019-07-30T18:57:31Z" level=debug msg="scheduler: Run job" job=job1 node=dkron-jobs-0 schedule="@every 10s"
time="2019-07-30T18:57:31Z" level=debug msg="store: Retrieved job from datastore" job=job1 node=dkron-jobs-0
time="2019-07-30T18:57:31Z" level=debug msg="agent: Filtered nodes to run: [dkron-jobs-0]" node=dkron-jobs-0
time="2019-07-30T18:57:31Z" level=debug msg="agent: Filtered tags to run: map[dkron_server:true:1]" node=dkron-jobs-0
time="2019-07-30T18:57:31Z" level=info msg="agent: Sending query" job_name=job1 node=dkron-jobs-0 query="run:job"
time="2019-07-30T18:57:31Z" level=debug msg="agent: Sending query" job_name=job1 json="{\"execution\":{\"job_name\":\"job1\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1564513051011245416,\"attempt\":1},\"rpc_addr\":\"172.30.103.10:6868\"}" node=dkron-jobs-0 query="run:job"
time="2019-07-30T18:57:31Z" level=info msg="agent: Received event" event="query: run:job" node=dkron-jobs-0
time="2019-07-30T18:57:31Z" level=debug msg="agent: Running job" at=2 node=dkron-jobs-0 payload="{\"execution\":{\"job_name\":\"job1\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1564513051011245416,\"attempt\":1},\"rpc_addr\":\"172.30.103.10:6868\"}" query="run:job"
time="2019-07-30T18:57:31Z" level=info msg="agent: Starting job" job=job1 node=dkron-jobs-0
time="2019-07-30T18:57:31Z" level=info msg="2019/07/30 18:57:31 [DEBUG] serf: messageQueryResponseType: dkron-jobs-0"
time="2019-07-30T18:57:31Z" level=debug msg="agent: Received ack" from=dkron-jobs-0 node=dkron-jobs-0 query="run:job"
time="2019-07-30T18:57:34Z" level=debug msg="agent: Done receiving acks and responses" node=dkron-jobs-0 query="run:job"
time="2019-07-30T18:57:36Z" level=error msg="grpc: error dialing." err="context deadline exceeded" node=dkron-jobs-0 server_addr="172.30.103.10:6868"
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x83cc62]

goroutine 142 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.18.0/clientconn.go:853 +0x42
panic(0x11529c0, 0x2012dc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
google.golang.org/grpc.(*ClientConn).Invoke(0x0, 0x16147a0, 0xc00009a010, 0x12f0cbf, 0x13, 0x1229820, 0xc0007da1b0, 0x12afa40, 0xc0001483c0, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.18.0/call.go:32 +0x38
github.com/victorcoder/dkron/proto.(*dkronClient).GetJob(0xc00000e6e0, 0x16147a0, 0xc00009a010, 0xc0007da1b0, 0x0, 0x0, 0x0, 0x202cc60, 0xc0003aea80, 0x3)
	/dkron/proto/dkron.pb.go:400 +0xd2
github.com/victorcoder/dkron/dkron.(*GRPCClient).CallGetJob(0xc0009b18e0, 0xc000690b80, 0x12, 0xc0003b2550, 0x4, 0x0, 0x0, 0x0)
	/dkron/dkron/grpc.go:272 +0x22c
github.com/victorcoder/dkron/dkron.(*Agent).eventLoop(0xc000114a80)
	/dkron/dkron/agent.go:472 +0x14e8
created by github.com/victorcoder/dkron/dkron.(*Agent).Start
	/dkron/dkron/agent.go:103 +0x3b9```

**Comment by mandeepbal** [comment]
I've updated to the latest version of dkron `v2.0.0-b6` and i'm still getting this `context deadline exceeded` error.

### Command
```
curl -X POST http://172.30.36.10:8089/v1/jobs -XPOST -d '{"name": "job1","schedule": "@every 10s",
"timezone": "Europe/Berlin","owner": "Platform Team","owner_email": "platform@example.com","disabled": false,"tags": {
"dkron_server": "true:1"},"concurrency": "allow","executor": "shell","executor_config": {"command": "date"}}'
```

### Container logs from startup
```
time="2019-07-31T19:21:09Z" level=info msg="No valid config found: Applying default values." error="Config File \"dkron\" Not Found in \"[/etc/dkron /root/.dkron /opt/local/dkron/config]\""
time="2019-07-31T19:21:09Z" level=debug msg="starting plugin" args="[/opt/local/dkron/dkron-processor-files]" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-files
time="2019-07-31T19:21:09Z" level=debug msg="plugin started" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-files pid=12
time="2019-07-31T19:21:09Z" level=debug msg="waiting for RPC address" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-files
time="2019-07-31T19:21:09Z" level=debug msg="plugin address" address=/tmp/plugin722792118 network=unix node=dkron-jobs-0 subsystem_name=plugins.dkron-processor-files timestamp="2019-07-31T19:21:09.149Z"
time="2019-07-31T19:21:09Z" level=debug msg="using plugin" node=dkron-jobs-0 version=1
time="2019-07-31T19:21:09Z" level=debug msg="starting plugin" args="[/opt/local/dkron/dkron-processor-log]" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-log
time="2019-07-31T19:21:09Z" level=debug msg="plugin started" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-log pid=21
time="2019-07-31T19:21:09Z" level=debug msg="waiting for RPC address" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-log
time="2019-07-31T19:21:09Z" level=debug msg="plugin address" address=/tmp/plugin406673241 network=unix node=dkron-jobs-0 subsystem_name=plugins.dkron-processor-log timestamp="2019-07-31T19:21:09.243Z"
time="2019-07-31T19:21:09Z" level=debug msg="using plugin" node=dkron-jobs-0 version=1
time="2019-07-31T19:21:09Z" level=debug msg="starting plugin" args="[/opt/local/dkron/dkron-processor-syslog]" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-syslog
time="2019-07-31T19:21:09Z" level=debug msg="plugin started" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-syslog pid=31
time="2019-07-31T19:21:09Z" level=debug msg="waiting for RPC address" node=dkron-jobs-0 path=/opt/local/dkron/dkron-processor-syslog
time="2019-07-31T19:21:09Z" level=debug msg="plugin address" address=/tmp/plugin666857681 network=unix node=dkron-jobs-0 subsystem_name=plugins.dkron-processor-syslog timestamp="2019-07-31T19:21:09.257Z"
time="2019-07-31T19:21:09Z" level=debug msg="using plugin" node=dkron-jobs-0 version=1
time="2019-07-31T19:21:09Z" level=debug msg="starting plugin" args="[/opt/local/dkron/dkron-executor-http]" node=dkron-jobs-0 path=/opt/local/dkron/dkron-executor-http
time="2019-07-31T19:21:09Z" level=debug msg="plugin started" node=dkron-jobs-0 path=/opt/local/dkron/dkron-executor-http pid=43
time="2019-07-31T19:21:09Z" level=debug msg="waiting for RPC address" node=dkron-jobs-0 path=/opt/local/dkron/dkron-executor-http
time="2019-07-31T19:21:09Z" level=debug msg="using plugin" node=dkron-jobs-0 version=1
time="2019-07-31T19:21:09Z" level=debug msg="plugin address" address=/tmp/plugin791436872 network=unix node=dkron-jobs-0 subsystem_name=plugins.dkron-executor-http timestamp="2019-07-31T19:21:09.300Z"
time="2019-07-31T19:21:09Z" level=info msg="agent: Dkron agent starting" node=dkron-jobs-0
time="2019-07-31T19:21:09Z" level=info msg="2019/07/31 19:21:09 [INFO] serf: EventMemberJoin: dkron-jobs-0 172.30.36.10"
time="2019-07-31T19:21:09Z" level=info msg="agent: joining: [dkron-jobs-service.default.svc.cluster.local:8946] replay: false" node=dkron-jobs-0
time="2019-07-31T19:21:09Z" level=info msg="2019/07/31 19:21:09 [WARN] memberlist: Failed to resolve dkron-jobs-service.default.svc.cluster.local:8946: lookup dkron-jobs-service.default.svc.cluster.local on 10.2.3.1:53: no such host"
time="2019-07-31T19:21:09Z" level=warning msg="agent: error joining: 1 error occurred:\n\t* Failed to resolve dkron-jobs-service.default.svc.cluster.local:8946: lookup dkron-jobs-service.default.svc.cluster.local on 10.254.3.100:53: no such host\n\n" node=dkron-jobs-0
badger 2019/07/31 19:21:09 INFO: All 0 tables opened in 0s
[GIN-debug] [WARNING] Now Gin requires Go 1.6 or later and Go 1.7 will be required soon.

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /debug/vars               --> github.com/gin-contrib/expvar.Handler.func1 (3 handlers)
[GIN-debug] GET    /health                   --> github.com/distribworks/dkron/dkron.(*HTTPTransport).APIRoutes.func1 (3 handlers)
[GIN-debug] GET    /v1                       --> github.com/distribworks/dkron/dkron.(*HTTPTransport).indexHandler-fm (3 handlers)
[GIN-debug] GET    /v1/                      --> github.com/distribworks/dkron/dkron.(*HTTPTransport).indexHandler-fm (3 handlers)
[GIN-debug] GET    /v1/members               --> github.com/distribworks/dkron/dkron.(*HTTPTransport).membersHandler-fm (3 handlers)
[GIN-debug] GET    /v1/leader                --> github.com/distribworks/dkron/dkron.(*HTTPTransport).leaderHandler-fm (3 handlers)
[GIN-debug] POST   /v1/leave                 --> github.com/distribworks/dkron/dkron.(*HTTPTransport).leaveHandler-fm (3 handlers)
[GIN-debug] POST   /v1/jobs                  --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobCreateOrUpdateHandler-fm (3 handlers)
[GIN-debug] PATCH  /v1/jobs                  --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobCreateOrUpdateHandler-fm (3 handlers)
[GIN-debug] GET    /v1/jobs                  --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobsHandler-fm (3 handlers)
[GIN-debug] DELETE /v1/jobs/:job             --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobDeleteHandler-fm (3 handlers)
[GIN-debug] POST   /v1/jobs/:job             --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobRunHandler-fm (3 handlers)
[GIN-debug] POST   /v1/jobs/:job/toggle      --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobToggleHandler-fm (3 handlers)
[GIN-debug] GET    /v1/jobs/:job             --> github.com/distribworks/dkron/dkron.(*HTTPTransport).jobGetHandler-fm (3 handlers)
[GIN-debug] GET    /v1/jobs/:job/executions  --> github.com/distribworks/dkron/dkron.(*HTTPTransport).executionsHandler-fm (3 handlers)
[GIN-debug] GET    /                         --> github.com/distribworks/dkron/dkron.(*Agent).DashboardRoutes.func1 (3 handlers)
[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] GET    /dashboard/               --> github.com/distribworks/dkron/dkron.(*Agent).dashboardIndexHandler-fm (3 handlers)
[GIN-debug] GET    /dashboard/jobs           --> github.com/distribworks/dkron/dkron.(*Agent).dashboardJobsHandler-fm (3 handlers)
[GIN-debug] GET    /dashboard/jobs/:job/executions --> github.com/distribworks/dkron/dkron.(*Agent).dashboardExecutionsHandler-fm (3 handlers)
time="2019-07-31T19:21:09Z" level=info msg="api: Running HTTP server" address=":8089" node=dkron-jobs-0
[GIN-debug] Listening and serving HTTP on :8089
time="2019-07-31T19:21:09Z" level=info msg="2019/07/31 19:21:09 [INFO] raft: Initial configuration (index=0): []"
time="2019-07-31T19:21:09Z" level=info msg="2019/07/31 19:21:09 [INFO] serf: EventMemberUpdate: dkron-jobs-0"
time="2019-07-31T19:21:09Z" level=info msg="dkron: monitoring leadership" node=dkron-jobs-0
time="2019-07-31T19:21:09Z" level=info msg="agent: Listen for events" node=dkron-jobs-0
time="2019-07-31T19:21:09Z" level=info msg="2019/07/31 19:21:09 [INFO] raft: Node at 172.30.36.10:6868 [Follower] entering Follower state (Leader: \"\")"
time="2019-07-31T19:21:10Z" level=info msg="agent: Received event" event=member-update node=dkron-jobs-0
time="2019-07-31T19:21:10Z" level=debug msg="agent: Member event" event=member-update member=dkron-jobs-0 node=dkron-jobs-0
time="2019-07-31T19:21:10Z" level=info msg="2019/07/31 19:21:10 [WARN] raft: no known peers, aborting election"






time="2019-07-31T19:22:01Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=dkron-jobs-0 server_addr=
time="2019-07-31T19:22:01Z" level=info msg="[GIN] 2019/07/31 - 19:22:01 | 422 |  5.000692467s |     172.30.87.0 | POST     /v1/jobs" node=dkron-jobs-0
time="2019-07-31T19:22:01Z" level=info msg="Error #01: context deadline exceeded" node=dkron-jobs-0
```

**Comment by victorcoder** [comment]
@brynette-stewart @mandeepbal are you still experiencing this error with latest versions?

**Comment by mandeepbal** [comment]
@victorcoder We haven't tested on the recent versions. We wanted to keep the dynamodb backend for dkron so we haven't upgraded.

**Comment by victorcoder** [comment]
@mandeepbal but you mentioned the error was in `v2.0.0-b6` which doesn't support DynamoDB, what do you mean?

Could you send me an email to victor at distrib.works?

**Comment by mandeepbal** [comment]
@victorcoder I think we can close this issue for now. @brynette-stewart and I haven't worked on this in a couple months. If we decide to pick up dkron again, we'll use the latest version and this most likely won't be an issue.
