### ISSUE TITLE
Non server agent crash on server agent failover

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#685]
**Describe the bug**
It looks that agent may crash, because it's trying to send ExecutionDone to a dead leader.
It's visible (for me) in a log that value of server_addr is an IP of an instance that is already dead.
The specifics of Kubernetes is that the IP of a container usually changes to a new one after it's restarted. Though it's possible to have same hostname for a new container.
```
time="2020-02-18T13:20:06Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=ExecutionDone node=dkron-6f45f67cfb-v6rf7 server_addr="172.25.8.124:6868"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8863c5]

goroutine 1741 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/clientconn.go:853 +0x45
github.com/distribworks/dkron/v2/dkron.(*GRPCClient).ExecutionDone(0xc000642be0, 0xc00023b860, 0x11, 0xc000161300, 0x2c4d7c0, 0x4060a20)
	/app/dkron/grpc_client.go:72 +0x49b
github.com/distribworks/dkron/v2/dkron.(*Agent).invokeJob(0xc0003e46c0, 0xc0004051e0, 0xc000161300, 0xc00061afc0, 0x80)
	/app/dkron/invoke.go:72 +0xcaa
github.com/distribworks/dkron/v2/dkron.(*Agent).eventLoop.func1(0xc0003e46c0, 0xc0004051e0, 0xc000161300)
	/app/dkron/agent.go:683 +0x5d
created by github.com/distribworks/dkron/v2/dkron.(*Agent).eventLoop
	/app/dkron/agent.go:682 +0x1c8b
```

**To Reproduce**
1. Run Dkron server in Kubernetes
2. Run Dkron agent in Kubernetes with provider=k8s discovery enabled. Agent automatically joins to cluster as a non-server and starts executing jobs.
3. Delete Dkron leader pod
4. If job is still executing in agent, it will crash with the error described above.

**Expected behavior**
Agent should send ExecutionDone to a new elected leader

** Specifications:**
 - OS: Linux
 - Environment: Kubernetes

**Comment by andreygolev** [comment]
Seems like it doesn't depend on whether it's a server failover, or just restart of any of server pod in a cluster. selectServerByKey chooses any server from a pool. And it may happen during restart of a server pod which not instantly remove record from Raft, resulting in old IP returned.

I've created workaround that checks if the peer is really alive. Not sure if it's the proper way with net.DialTimeout, but at least it's something :)

```
diff dkron/invoke.go ../dkron-fork/dkron/dkron/invoke.go
4a5
> 	"net"
64c65
< 	rpcServer, err := a.selectServerByKey(execution.Key())
---
> 	rpcServer, err := a.checkAndSelectServer()
89a91,108
>
> func (a *Agent) checkAndSelectServer() (string, error) {
> 	var peers []string
> 	for _, p := range a.LocalServers() {
> 		peers = append(peers, p.RPCAddr.String())
> 	}
>
> 	for _, peer := range peers {
> 		log.Debugf("Checking peer: %v", peer)
> 		conn, err := net.DialTimeout("tcp", peer, 5*time.Second)
> 		if err == nil {
> 			conn.Close()
> 			log.Debugf("Found good peer: %v", peer)
> 			return peer, nil
> 		}
> 	}
> 	return "", ErrNoSuitableServer
> }
```

**Comment by andreygolev** [comment]
Also server may crash multiple times after it's gracefully restarted.
```
time="2020-02-19T10:43:37Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=ExecutionDone node=dkron-server-2 server_addr=
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x886515]

goroutine 112 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/clientconn.go:853 +0x45
github.com/distribworks/dkron/v2/dkron.(*GRPCClient).ExecutionDone(0xc0002084e0, 0x0, 0x0, 0xc000146880, 0x2c4d580, 0x405fa20)
	/app/dkron/grpc_client.go:72 +0x49b
github.com/distribworks/dkron/v2/dkron.(*GRPCServer).ExecutionDone(0xc00000e688, 0x2c94440, 0xc0005d4870, 0xc0005d48a0, 0x0, 0x0, 0x0)
	/app/dkron/grpc.go:156 +0x1b52
github.com/distribworks/dkron/v2/proto._Dkron_ExecutionDone_Handler(0x25ac9a0, 0xc00000e688, 0x2c94440, 0xc0005d4870, 0xc000560960, 0x0, 0x2c94440, 0xc0005d4870, 0xc00029e5b0, 0xcc)
	/app/proto/dkron.pb.go:1393 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005ac180, 0x2cb9500, 0xc0005acf00, 0xc00014c800, 0xc0005b1980, 0x40198d8, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:971 +0x46a
google.golang.org/grpc.(*Server).handleStream(0xc0005ac180, 0x2cb9500, 0xc0005acf00, 0xc00014c800, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:1250 +0xd16
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005e8090, 0xc0005ac180, 0x2cb9500, 0xc0005acf00, 0xc00014c800)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:690 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:688 +0xa1
```

server_addr value is empty there, but server already receives ExecutionDone, causing panics.
Panic itself seems to be caused by calling "defer conn.Close()" on a non existent connection.
So I removed "defer conn.Close()" and added explicit conn.Close() to places where it's possible to close connection and so far no panics, and just few "gprc: dialing error" errors after server restart.

dkron/grpc_client.go
```
// ExecutionDone calls the ExecutionDone gRPC method
func (grpcc *GRPCClient) ExecutionDone(addr string, execution *Execution) error {
	defer metrics.MeasureSince([]string{"grpc", "call_execution_done"}, time.Now())
	var conn *grpc.ClientConn

	conn, err := grpcc.Connect(addr)
	if err != nil {
		log.WithError(err).WithFields(logrus.Fields{
			"method":      "ExecutionDone",
			"server_addr": addr,
		}).Error("grpc: error dialing.")
		return err
	}

	d := proto.NewDkronClient(conn)
	edr, err := d.ExecutionDone(context.Background(), &proto.ExecutionDoneRequest{Execution: execution.ToProto()})
	if err != nil {
		if err.Error() == fmt.Sprintf("rpc error: code = Unknown desc = %s", ErrNotLeader.Error()) {
			log.Info("grpc: ExecutionDone forwarded to the leader")
			conn.Close()
			return nil
		}

		log.WithError(err).WithFields(logrus.Fields{
			"method":      "ExecutionDone",
			"server_addr": addr,
		}).Error("grpc: Error calling gRPC method")
		return err
	}
	log.WithFields(logrus.Fields{
		"method":      "ExecutionDone",
		"server_addr": addr,
		"from":        edr.From,
		"payload":     string(edr.Payload),
	}).Debug("grpc: Response from method")
	conn.Close()
	return nil
}
```

**Comment by andreygolev** [comment]
Fixed in https://github.com/distribworks/dkron/pull/691
Fixed in https://github.com/distribworks/dkron/pull/693

**Comment by victorcoder** [comment]
Thanks
