### ISSUE TITLE
Server crash when adding new job

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#819]
**Describe the bug**
Sometimes, server may crash when adding new jobs. It doesn't depend on job amount we add. We can add 70 jobs at once and it will be fine, but sometimes we can add 1,2,3 jobs and server may crash. Server is scheduling around 5 jobs simulatenously each seconds to give a estimation of our workload on scheduler.

This is the beginning of trace.  (won't paste there, as it throws all the goroutines, and very huge)
```
fatal error: concurrent map read and map write
goroutine 63870466 [running]:
runtime.throw(0x2a7dda7, 0x21)
/usr/local/go/src/runtime/map_faststr.go:116 +0x47c fp=0xc00099b778 sp=0xc00099b708 pc=0x412f0c
runtime.mapaccess2_faststr(0x2486e80, 0xc000d2a240, 0xc0013c50c0, 0x19, 0xd0, 0xc001893ee0)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00099b708 sp=0xc00099b6d8 pc=0x433a62
github.com/distribworks/dkron/v3/dkron.(*GRPCServer).SetJob(0xc000dbc690, 0x341f5c0, 0xc0018997d0, 0xc001899800, 0x0, 0x0, 0x0)
/app/plugin/types/dkron.pb.go:1602 +0x217 fp=0xc00099bbb0 sp=0xc00099bb40 pc=0x95c6b7
runtime.goexit()
/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1
/app/dkron/grpc.go:95 +0x2e8 fp=0xc00099bb40 sp=0xc00099b950 pc=0x1f898d8
/app/cmd/agent.go:84 +0x1d6
github.com/distribworks/dkron/v3/cmd.agentRun(0xc0004ccee0, 0x0, 0x7, 0x0, 0x0)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
/app/cmd/dkron.go:32 +0x31
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000996b60, 0x343f180, 0xc0034a8f00, 0xc001357200, 0xc000dbc7b0, 0x492ba08, 0x0, 0x0, 0x0)
/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccb fp=0xc00099bf68 sp=0xc00099be40 pc=0x942d9b
/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1 fp=0xc00099bfb8 sp=0xc00099bf68 pc=0x950621
created by google.golang.org/grpc.(*Server).serveStreams.func1
goroutine 1 [select, 110991 minutes]:
/app/cmd/agent.go:68 +0x18c
github.com/distribworks/dkron/v3/cmd.glob..func1(0x492d6c0, 0xc0004ccee0, 0x0, 0x7, 0x0, 0x0)
github.com/spf13/cobra.(*Command).ExecuteC(0x492d960, 0x442c6a, 0x48b3380, 0xc00006a778)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
/app/main.go:9 +0x20
github.com/distribworks/dkron/v3/cmd.Execute()
goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x4954320)
/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
github.com/distribworks/dkron/v3/dkron.(*Scheduler).AddJob(0xc000911360, 0xc0016ea300, 0x0, 0x0)
github.com/distribworks/dkron/v3/plugin/types._Dkron_SetJob_Handler(0x2895f00, 0xc000dbc690, 0x341f5c0, 0xc0018997d0, 0xc001468a20, 0x0, 0x341f5c0, 0xc0018997d0, 0xc001185680, 0x171)
google.golang.org/grpc.(*Server).handleStream(0xc000996b60, 0x343f180, 0xc0034a8f00, 0xc001357200, 0x0)
/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x50a fp=0xc00099be40 sp=0xc00099bbb0 pc=0x93ec0a
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0018eb2d0, 0xc000996b60, 0x343f180, 0xc0034a8f00, 0xc001357200)
/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00099bfc0 sp=0xc00099bfb8 pc=0x463e31
github.com/distribworks/dkron/v3/cmd.handleSignals(0xc000360140)
/app/cmd/agent.go:38 +0x3f
github.com/spf13/cobra.(*Command).execute(0x492d6c0, 0xc0004cce70, 0x7, 0x7, 0x492d6c0, 0xc0004cce70)
main.main()
/app/dkron/scheduler.go:94 +0x6c fp=0xc00099b950 sp=0xc00099b778 pc=0x1fa401c
created by github.com/golang/glog.init.0
internal/poll.(*pollDesc).wait(0xc00008b098, 0x72, 0x10001, 0x10000, 0xffffffffffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*pollDesc).waitRead(...)
os.(*File).read(...)
/usr/local/go/src/os/file_unix.go:263
bufio.(*Reader).ReadSlice(0xc000b96f40, 0xc00033490a, 0xc000b96e00, 0x1f977ef, 0xc000168070, 0x5, 0xc000b96df0)
```

**Comment by victorcoder** [comment]
This is weird, I understand that they are new jobs, not existing ones, it should be related to your kind of workload. I need to  investigate.

**Comment by wintheday** [comment]
@victorcoder We experienced this issue as well.  If you need additional logs or context to help debug let me know.

**Comment by prakashdivyy** [comment]
any updates on this @victorcoder ?

**Comment by victorcoder** [comment]
not yet sorry

**Comment by reyhansofian** [comment]
@victorcoder are you planning to release this fix anytime soon? Because we need this fix to be applied to our system soon. Thanks!

**Comment by victorcoder** [comment]
@reyhansofian Released in v3.0.7

**Comment by reyhansofian** [comment]
thanks a lot @victorcoder !

**Comment by lzyrapx** [comment]
@victorcoder hi, victor. Could you please explain the cause of this bug? Thanks in advance.
